repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/gitleaks/gitleaks
    rev: 6eaad039603a4de39fddd1cf5f727391efe9974e  # v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: f298c082154b2cb239fac06a4f452368e66e66dd  # v1.0.0-rc.4
    hooks:
      - id: go-fmt
      - id: go-vet-mod
